name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggers

env:
  AZURE_WEBAPP_NAME: short-url  # Set your Azure Web App name
  AZURE_RESOURCE_GROUP: short-url_group  # Set your Azure Resource Group name
  AZURE_REGION: East US  # Set your Azure region
  PYTHON_VERSION: '3.12'  # Specify the Python version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the application
      run: python main.py

    - name: Azure Web App Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Restart Azure Web App
      uses: azure/cli@v1
      with:
        azcliversion: 2.0.80
        inlineScript: az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

